"""contracts relationship with users added

Revision ID: 329ad8c88ab2
Revises: f4a45ba6b034
Create Date: 2025-08-18 20:10:36.836848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '329ad8c88ab2'
down_revision: Union[str, Sequence[str], None] = 'f4a45ba6b034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'contracts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'user_id')
    # ### end Alembic commands ###
