"""modified relatioships rules

Revision ID: ec37778b5177
Revises: 24562014640c
Create Date: 2025-08-16 00:42:03.592983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec37778b5177'
down_revision: Union[str, Sequence[str], None] = '24562014640c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'supplier_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'supplier_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
