"""create services table

Revision ID: 88d115268f6c
Revises: 449e95442886
Create Date: 2025-08-12 22:16:08.872785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88d115268f6c'
down_revision: Union[str, Sequence[str], None] = '449e95442886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_r_contracts_id'), table_name='r_contracts')
    op.drop_table('r_contracts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('r_contracts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('r_contracts_client_id_fkey')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('r_contracts_service_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('r_contracts_pkey'))
    )
    op.create_index(op.f('ix_r_contracts_id'), 'r_contracts', ['id'], unique=False)
    # ### end Alembic commands ###
