"""user relationship updated with default value to client columns

Revision ID: 964908d68be4
Revises: 168344ff6713
Create Date: 2025-09-05 19:28:42.475881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '964908d68be4'
down_revision: Union[str, Sequence[str], None] = '168344ff6713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('user_id', sa.Integer(), server_default='0', nullable=False))
    op.create_index(op.f('ix_clients_user_id'), 'clients', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clients_user_id'), table_name='clients')
    op.drop_column('clients', 'user_id')
    # ### end Alembic commands ###
